{
    "output": "",
    "errors": "E\n======================================================================\nERROR: test_delete_duplicates (__main__.TestSolution.test_delete_duplicates)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\82_remove-duplicates-from-sorted-list-ii\\test.py\", line 67, in setUp\n    from solution import Solution\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\82_remove-duplicates-from-sorted-list-ii\\solution.py\", line 2, in <module>\n    class Solution:\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\82_remove-duplicates-from-sorted-list-ii\\solution.py\", line 4, in Solution\n    def deleteDuplicates(self, head: ListNode) -> ListNode:\n                                     ^^^^^^^^\nNameError: name 'ListNode' is not defined\n\n----------------------------------------------------------------------\nRan 1 test in 0.027s\n\nFAILED (errors=1)\n",
    "returncode": 1
}